version: '3.8'

services:
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
      # - "443:443"
    volumes:
      - ./.volumes/minio/data:/data
      - ./.docker/minio/certs:/root/.minio/certs/
      # - ~/minio/certs:/root/.minio/certs/CAs
    environment:
      MINIO_ROOT_USER: dev
      MINIO_ROOT_PASSWORD: 123456aA@
#      MINIO_BROWSER_REDIRECT_URL: https://storage.nerdcloud.co/minio
#      MINIO_DOMAIN: storage.nerdcloud.co
#      MINIO_SERVER_URL: https://storage.nerdcloud.co
    command: server /data --console-address ":9090"
